version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_USERNAME=k6bvq3m7gt68c3ufqzms
      - DB_PASSWORD=pscale_pw_nq2WLXxz1Bge9Wa9vYzvGRPZga2m8DP526QPoNEFvtc
      - DB_NAME=kiymeshek
      - DB_HOST=aws.connect.psdb.cloud
      - DB_PORT=3306
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kiymeshek
      - MYSQL_USER=k6bvq3m7gt68c3ufqzms
      - MYSQL_PASSWORD=pscale_pw_nq2WLXxz1Bge9Wa9vYzvGRPZga2m8DP526QPoNEFvtc
    ports:
      - 3306:3306

